-- NOME E RA:
-- GUILHERME MIDEA PAOLIELLO CASTILHO  2200770
-- AMÁLIA EMÍLIA DA ROCHA PITTA        2200519


SELECT * FROM #ESTADO
SELECT * FROM #CIDADE
SELECT * FROM #ENDERECO
SELECT * FROM #CLIENTE
SELECT * FROM #MAQUINA
SELECT * FROM #PEDIDO
SELECT * FROM #ITEM_PEDIDO
SELECT * FROM #CLIENTES_CADASTRO_ATUALIZADO
SELECT * FROM #FABRICANTE


UPDATE #ESTADO SET SIGLA = 'MG' WHERE ESTADO = 'MINAS GERAIS'

UPDATE #CIDADE SET CIDADE = 'RIO CLARO' WHERE ID_CIDADE = '4'

UPDATE #ENDERECO SET NUMERO = '560' WHERE ID_ENDERECO = '7'

UPDATE #CLIENTE SET DATA_CADASTRO = '2012-01-01' WHERE DATA_CADASTRO IS NULL

UPDATE #MAQUINA SET DESCRICAO = 'Jukebox dos anos 50 em acabamento refinado' WHERE CODIGO = '30'

ALTER TABLE #PEDIDO ADD DESCONTO VARCHAR(10)
UPDATE #PEDIDO SET DESCONTO = VALOR * 10/100
UPDATE #PEDIDO SET VALOR_TOTAL = VALOR - DESCONTO

------

DELETE FROM #ITEM_PEDIDO WHERE ID_PEDIDO = '7'

DELETE FROM #PEDIDO WHERE ID_PEDIDO = '7'

DELETE FROM #CLIENTE WHERE ID_CLIENTE = '6'

---

CREATE TABLE #CLIENTES_CADASTRO_ATUALIZADO
(CNPJ_CPF VARCHAR(50) NOT NULL,
NOME VARCHAR(100),
DATA_NASCIMENTO DATE)

INSERT INTO #CLIENTES_CADASTRO_ATUALIZADO 
SELECT CNPJ_CPF, NOME, DATA_NASCIMENTO FROM #CLIENTE
WHERE DATA_NASCIMENTO < '1990-01-01'

SELECT ID_MAQUINA, CODIGO, NOME FROM #MAQUINA WHERE DESCRICAO LIKE '%PEBOLIM%'

SELECT NOME, DATA_NASCIMENTO FROM #CLIENTE
WHERE DATA_NASCIMENTO < '1995-01-01'

CREATE TABLE #FABRICANTE
(ID_FABRICANTE INT IDENTITY PRIMARY KEY,
NOME_FABRICANTE VARCHAR(500) UNIQUE,
PAIS VARCHAR(500) NOT NULL)

INSERT INTO #FABRICANTE (NOME_FABRICANTE, PAIS) VALUES('DELL','EUA')
INSERT INTO #FABRICANTE (NOME_FABRICANTE, PAIS) VALUES('LENOVO','EUA')
INSERT INTO #FABRICANTE (NOME_FABRICANTE, PAIS) VALUES('SAMSUNG','COREIA')