
/*
NOME E RA DOS ALUNOS
-- Amália E. R. Pitta 2200519
-- Guilherme M. P. Castilho 2200770
*/


/*
Resposta - 1
*/

SELECT
(C.PRIMEIRO_NOME + ' ' + C.MEIO_NOME + ' ' + C.ULTIMO_NOME) NOME_COMPLETO,
PE.DATA_PEDIDO,
PE.NUMERO_PEDIDO,
(SUM(DP.QUANTIDADE_PEDIDO) * DP.PRECO_UNITARIO) TOTAL_PEDIDO,
CP.NOME NOME_CATEGORIA
FROM VENDA.CLIENTE AS C
INNER JOIN VENDA.PEDIDO AS PE ON C.ID_CLIENTE = PE.ID_CLIENTE
INNER JOIN VENDA.DETALHE_PEDIDO AS DP ON PE.ID_PEDIDO = DP.ID_PEDIDO
INNER JOIN VENDA.PRODUTO AS P ON DP.ID_PRODUTO = P.ID_PRODUTO
INNER JOIN VENDA.CATEGORIA_PRODUTO AS CP ON P.ID_CATEGORIA_PRODUTO = CP.ID_CATEGORIA_PRODUTO
GROUP BY C.PRIMEIRO_NOME, C.MEIO_NOME, C.ULTIMO_NOME, PE.DATA_PEDIDO, PE.NUMERO_PEDIDO, CP.NOME, DP.PRECO_UNITARIO

/*
Resposta - 2
*/

CREATE TABLE #DIRETORIA
(ID_DIRETORIA INT PRIMARY KEY IDENTITY,
NOME_DIRETORIA VARCHAR(200) NOT NULL,
DATA_CADASTRO DATE)

INSERT INTO #DIRETORIA (NOME_DIRETORIA) VALUES ('MATRIZ')
INSERT INTO #DIRETORIA (NOME_DIRETORIA, DATA_CADASTRO) VALUES ('REGIONAL 1', '2022-01-01')
INSERT INTO #DIRETORIA (NOME_DIRETORIA, DATA_CADASTRO) VALUES ('REGIONAL 2', '2022-03-08')
INSERT INTO #DIRETORIA (NOME_DIRETORIA, DATA_CADASTRO) VALUES ('REGIONAL 3', '2022-04-08')

UPDATE #DIRETORIA
SET #DIRETORIA.DATA_CADASTRO = '2021-01-01'
WHERE #DIRETORIA.ID_DIRETORIA = 1

SELECT * FROM #DIRETORIA

/*
Resposta - 3
*/

SELECT
P.NOME NOME_PRODUTO,
MP.NOME NOME_MODELO,
CP.NOME NOME_CATEGORIA,
P.CUSTO_PADRAO,
DATEDIFF(YEAR,GETDATE(),P.DATA_INICIO_VENDA) ANOS_VENDA
FROM VENDA.PRODUTO AS P
INNER JOIN VENDA.MODELO_PRODUTO AS MP ON P.ID_MODELO_PRODUTO = MP.ID_MODELO_PRODUTO
INNER JOIN VENDA.CATEGORIA_PRODUTO AS CP ON P.ID_CATEGORIA_PRODUTO = CP.ID_CATEGORIA_PRODUTO 
LEFT JOIN VENDA.DETALHE_PEDIDO AS DP ON P.ID_PRODUTO = DP.ID_PRODUTO
WHERE QUANTIDADE_PEDIDO IS NULL

/*
Resposta - 4
*/

SELECT
C.COMPANHIA COMPANHIA_CLIENTE,
SUM(CASE WHEN P.COR = 'Black' THEN DP.QUANTIDADE_PEDIDO ELSE 0 END) SOMA_COR,
SUM(DP.QUANTIDADE_PEDIDO) SOMA_TOTAL
FROM VENDA.CLIENTE AS C
INNER JOIN VENDA.PEDIDO AS PE ON C.ID_CLIENTE = PE.ID_CLIENTE
INNER JOIN VENDA.DETALHE_PEDIDO AS DP ON PE.ID_PEDIDO = DP.ID_PEDIDO
INNER JOIN VENDA.PRODUTO AS P ON DP.ID_PRODUTO = P.ID_PRODUTO
GROUP BY C.COMPANHIA

/*
Resposta - 5
*/

SELECT 
C.PRIMEIRO_NOME,
C.ULTIMO_NOME,
E.CIDADE,
E.ESTADO,
E.REGIAO
FROM VENDA.CLIENTE AS C
INNER JOIN VENDA.CLIENTE_ENDERECO AS CE ON C.ID_CLIENTE = CE.ID_CLIENTE
INNER JOIN VENDA.ENDERECO AS E ON CE.ID_ENDERECO = E.ID_ENDERECO
WHERE E.REGIAO = 'United States' AND E.ESTADO = 'Texas'
